spring.application.name=lab
spring.datasource.url=jdbc:postgresql://localhost:5432/anti_procrastinator_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=${JWT_SECRET:v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYp}
app.jwt.expirationMs=86400000

springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.display-request-duration=true
springdoc.packages-to-scan=com.antiprocrastinate.lab.controller,com.antiprocrastinate.lab.dto
springdoc.paths-to-match=/api/**
springdoc.show-actuator=false

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB