spring.application.name=lab
spring.datasource.url=jdbc:postgresql://localhost:5432/anti_procrastinator_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true